# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/scoiaz/python/ericWS/formImage/imgForm1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 530)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.Page1 = QtWidgets.QWidget()
        self.Page1.setObjectName("Page1")
        self.listImages = QtWidgets.QListWidget(self.Page1)
        self.listImages.setGeometry(QtCore.QRect(10, 10, 531, 221))
        self.listImages.setObjectName("listImages")
        self.lblMainImage = QtWidgets.QLabel(self.Page1)
        self.lblMainImage.setGeometry(QtCore.QRect(550, 50, 181, 181))
        self.lblMainImage.setText("")
        self.lblMainImage.setObjectName("lblMainImage")
        self.listFaces = QtWidgets.QListWidget(self.Page1)
        self.listFaces.setGeometry(QtCore.QRect(10, 240, 531, 181))
        self.listFaces.setObjectName("listFaces")
        self.lblFaceImage = QtWidgets.QLabel(self.Page1)
        self.lblFaceImage.setGeometry(QtCore.QRect(550, 240, 181, 181))
        self.lblFaceImage.setText("")
        self.lblFaceImage.setObjectName("lblFaceImage")
        self.txtImgFaceName = QtWidgets.QLineEdit(self.Page1)
        self.txtImgFaceName.setGeometry(QtCore.QRect(14, 440, 531, 26))
        self.txtImgFaceName.setText("")
        self.txtImgFaceName.setObjectName("txtImgFaceName")
        self.label_2 = QtWidgets.QLabel(self.Page1)
        self.label_2.setGeometry(QtCore.QRect(14, 420, 111, 18))
        self.label_2.setObjectName("label_2")
        self.btnFindImages = QtWidgets.QPushButton(self.Page1)
        self.btnFindImages.setGeometry(QtCore.QRect(546, 10, 191, 26))
        self.btnFindImages.setObjectName("btnFindImages")
        self.btnSaveName = QtWidgets.QPushButton(self.Page1)
        self.btnSaveName.setGeometry(QtCore.QRect(550, 440, 191, 26))
        self.btnSaveName.setObjectName("btnSaveName")
        self.tabWidget.addTab(self.Page1, "")
        self.Page2 = QtWidgets.QWidget()
        self.Page2.setObjectName("Page2")
        self.tabWidget.addTab(self.Page2, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Page1.setAccessibleName(_translate("MainWindow", "Page1"))
        self.Page1.setAccessibleDescription(_translate("MainWindow", "Page1"))
        self.label_2.setText(_translate("MainWindow", "Face Name"))
        self.btnFindImages.setText(_translate("MainWindow", "Select Images"))
        self.btnSaveName.setText(_translate("MainWindow", "Assign Name"))
        self.Page2.setAccessibleName(_translate("MainWindow", "Page2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
